# reference from : https://medium.com/@kicsipixel/install-pgadmin-with-postgresql-database-using-docker-ded3e2dfbe3b
# ตอน connection server ให้ใส่ IP จริง
# .env.production

# # PostgreSQL database
# PGDATA=/var/lib/postgresql/data/pgdata
# POSTGRES_USER=admin
# POSTGRES_PASSWORD=admin_passw0rd
# POSTGRES_DB=pg_database
# POSTGRES_HOST=localhost
# # pgAdmin
# PGADMIN_DEFAULT_EMAIL=pgAdmin@mail.com
# PGADMIN_DEFAULT_PASSWORD=pgAdmin_secr3t


version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env.production
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
volumes:
  db_data:
  pgadmin-data:
